name: vaultwarden
services:
  vaultwarden:
    image: vaultwarden/server:latest
    network_mode: bridge
    container_name: vaultwarden
    hostname: vaultwarden
    environment:
      TZ: ${TZ}
      DATABASE_URL: "postgresql://${VAULTWARDEN_DB_NAME}:${VAULTWARDEN_DB_NAME}@${LOCALHOST}:${POSTGRES_PORT}/${VAULTWARDEN_DB_NAME}"
    ports:
      - 10380:80
    volumes:
      - type: bind
        source: "${BASEPATH}/${APP_CONFIG_PATH}"
        target: /data
    restart: unless-stopped
    labels:
      proxy.#1.port: 10380
      proxy.idle_timeout: 45m
      proxy.#1.middlewares.forward_auth: |
        route: tinyauth
        auth_endpoint: /api/auth/traefik
        headers: Remote-User, Remote-Name, Remote-Email, Remote-Groups
        bypass: path glob(/identity/**)